language: c

compiler:
    - clang
    - gcc

env:
    - PT_PHP_VERSION=5.2.17
    - PT_PHP_VERSION=5.3.29
    - PT_PHP_VERSION=5.4.37
    - PT_PHP_VERSION=5.5.33
    - PT_PHP_VERSION=5.6.19
    - PT_PHP_VERSION=7.0.4

before_install:
    # build PHP without ZTS by ourselves...
    - ./.travis/php_get.sh ${PT_PHP_VERSION}
    - ./.travis/php_build.sh `pwd` php-${PT_PHP_VERSION}.tar.bz2
    - PT_PHP_PATH=`pwd`/php-${PT_PHP_VERSION}
    - PT_PHP_BIN=${PT_PHP_PATH}/bin/php

before_script:
    - ./.travis/ext_build.sh extension ${PT_PHP_PATH}
    - (cd extension && make cli)

script:
    - (cd ${PT_PHP_PATH} && TEST_PHP_EXECUTABLE=${PT_PHP_BIN} ${PT_PHP_BIN} -n run-tests.php -q -n -d extension=trace.so -g "FAIL" --show-diff --set-timeout 120 tests Zend/tests; true)
    - (cd extension && REPORT_EXIT_STATUS=1 TEST_PHP_EXECUTABLE=${PT_PHP_BIN} ${PT_PHP_BIN} -n run-tests.php -q -n -d extension=trace.so --show-diff)
